version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql
    container_name: test-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 15

  # Service 1
  categories:
    image: vierpaspuel/categories
    container_name: c-app-categories
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT : 8003
      DB_HOST: test-db:3306
    ports:
      - "8082:8003"
    networks:
      - test-network
    restart: unless-stopped

  # Service 2
  products:
    image: vierpaspuel/products
    container_name: c-app-products
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT : 8003
      DB_HOST: test-db:3306
      C_APP_CATEGORIES: c-app-categories:8003
    ports:
      - "8081:8003"
    networks:
      - test-network
    restart: unless-stopped

  # API Gateway
  gateway:
    image: vierpaspuel/gateway
    container_name: gateway
    depends_on:
      - products
      - categories
    ports:
      - "8080:8080"
    networks:
      - test-network
    restart: unless-stopped

  # Angular Application
  frontend:
    image: vierpaspuel/frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - test-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  test-network:
    driver: bridge

